/*jslint node: true */
"use strict";

// Seed math

exports.random = x => {
    return x * Math.random();
};

exports.randomAngle = () => {
    return Math.PI * 2 * Math.random();
};
exports.chooseBuild = (build) => {
  return [1,1,1,1,1,1,1,1]

};
exports.chooseTank = (tank) => {
  let tanks = [
    "basic",
    "twin",
    "sniper",
    "machine",
    "pounder",
    "director",
    "flank",
    "double",
    "hexa",
    "bent",
    "pellet",
    "assassin",
    "mini",
    "builder",
    "hunter",
    "destroyer",
    "artillery",
    "flankPound",
    "gunner",
    "blaster",
    "hexa",
    "tri",
    "auto3",
    "flankTrap",
    "overseer",
    "cruiser",
    "underseer",
    "littleFactory",
    "zoomSingle",
    "dual",
    "twinSniper",
    "bulwark",
    "insect",
    "flankDestroy",
    "tripleTwin",
    "autoDouble",
    "battleship",
    "penta",
    "spread",
    "bentHybrid",
    "bentDouble",
    "triplet",
    "sunburst",
    "bentBlaster",
    "autoGunner",
    "nailgun",
    "auto4",
    "machineGunner",
    "guntrap",
    "hurricane",
    "battery",
    "snipeGuard",
    "predator",
    "poach",
    "rocketeer",
    "skimmer",
    "shift",
    "demoman",
    "carnivore",
    "devastator",
    "construct",
    "autoBuilder",
    "engineer",
    "boomer",
    "twinBuilder",
    "mechaTrap",
    "musket",
    "spray",
    "autoMachine",
    "flooder",
    "dualBlaster",
    "gatling",
    "annihilator",
    "hybrid",
    "shotgun",
    "autoDestroy",
    "hiveShooter",
    "steamroll",
    "sheller",
    "mortar",
    "autoArtillery",
    "intercept",
    "cannon",
    "stream",
    "hybridMini",
    "autoMini",
    "autoMaton",
    "silo",
    "hotshot",
    "master",
    "triCruiser",
    "fighter",
    "booster",
    "autoTri",
    "falconBot",
    "bomber",
    "surfer",
    "auto5",
    "heavy3",
    "sniper3",
    "builder3",
    "machine3",
    "shuriken",
    "banshee",
    "fortress",
    "chimera",
    "factory",
    "sniperFactory",
    "machineFactory",
    "overlord",
    "overtrap",
    "overgunner",
    "autoOverseer",
    "manager",
    "necromancer",
    "autoUnderseer",
    "carrier",
    "autoCruiser",
    "fatCruiser",
    "autoSmash",
    "octo",
    "miniSpread",
    "autoMiniSpread",
    "spreadbow",
    "autoPellet",
    "griefer",
    "nightseeker",
    "sounder",
    "boxer",
    "guardSpreadling",
    "charger",
    "volcano",
    "howitzer",
    "newScaler",
    "dreadnought",
    "trapperFactory",
    "spreadTrap",
    "hewnGunner",
    "heavyRifle",
    "gunRifle",
    "spreadRifle",
    "assaultRifle",
    "sniperRifle",
    "stalkRifle",
    "beehive",
    "triMachine",
    "blasterSpray",
    "railgun",
    "autoPounder",
    "autoFlankPound",
    "triPellet",
    "pentaPellet",
    "gunborer",
    "scorpion",
    "piercer",
    "punter",
    "puntMini",
    "sword",
    "warship",
    "moonburst",
    "autoBorer",
    "autoPunt",
    "autoHewnPellet",
    "autoSail",
    "hybridPellet",
    "hybridBorer",
    "hybridPunt",
    "hybridHewnPellet",
    "hybridSail",
    "split",
    "clicker",
    "rifleClicker",
    "megaClicker",
    "longClicker",
    "eagleBot",
    "aagun",
    "fieldGun",
    "autoRifle",
    "hybridRifle",
    "hybridAssassin",
    "hybridBuilder",
    "lightning",
    "littleSkimmer",
    "autoLauncher",
    "fatSkimmer",
    "poundAngle",
    "autoTwinSniper",
    "twinAssassin",
    "trapper",
    "triTrapper",
    "autoTrapper",
    "obliterator",
    "plow",
    "crusher",
    "bulldozer",
    "twister",
    "miniClicker",
    "doubleGuard",
    "triContagion",
    "contagion",
    "autoContagion",
    "droneTrapper",
    "fort",
    "longBorer",
    "multishot",
    "machshot",
    "buckshot",
    "miniMultishot",
    "megaTrapper",
    "autoMegaTrapper",
    "gigaTrapper",
    "megaContagion",
    "plaguer",
    "triRocket",
    "spreadHunter",
    "maleficitor",
    "refractor",
    "flankBuilder",
    "swarmBuilder",
    "swarmMegaTrapper",
    "swarmContagion",
    "twinSpreadling",
    "heavyTwin",
    "fastGatling",
    "gatlingSpray",
    "autoSpray",
    "twinFactory",
    "rifleTrap",
    "swarmArtillery",
    "twinRifle",
    "overdrive",
    "conquerorBot",
    "thrower",
    "trapSkimmer",
    "hybridArtillery",
    "twinTrapper",
    "twinContagion",
    "swarmTwinTrapper",
    "longContagion",
    "diver",
    "doubleSwarm",
    "trapperSwarm",
    "heavyOverseer",
    "submarine",
    "manyshot",
    "undergunner",
    "undertrap",
    "machTrapper",
    "blasterTrapper",
    "gatlingTrapper",
    "machBuilder",
    "bentTrapper",
    "doubleTrapper",
    "autoMachTrapper",
    "autoTwinTrapper",
    "trapperAutoTrapper",
    "marine",
    "torpedoer",
    "triBorer",
    "triHewnPellet",
    "triPunt",
    "quintuplet",
    "megaAnnihilator",
    "twinRanger",
    "snipewark",
    "starbomber",
    "quadTwin",
    "hyperSkimmer",
    "rangerGatling",
    "wideSpread",
    "longRanger",
    "auto7",
    "autoDoubleTrapper",
    "bentTrapper",
    "streamTrap",
    "clover",
    "miniBuilder",
    "heavy5",
    "sniper5",
    "machine5",
    "auto6",
    "assassin3",
    "obliterator3",
    "overwork",
    "hottershot",
    "hybridStream",
    "builderFactory",
    "boostRocket",
    "longHotshot",
    "smother",
    "tripleDual",
    "siloStream",
    "heavyOverlord",
    "hexaDestroy",
    "hexaPound",
    "autoHexaTrap",
    "hexaTrap",
    "octoTrap",
    "xPredator",
    "spreadMach",
    "teraTrapper",
    "trapdrive",
    "gundrive",
    "harddrive",
    "hyperdrive",
    "juggernaut",
    "megaBarricade",
    "fatFactory",
    "hybridBarricade",
    "autoHeavyDouble",
    "heavyDouble",
    "flankAnni",
    "wideCannon",
    "twinTri",
    "shellerMortar",
    "anniSheller",
    "pentaSunburst",
    "zoomTwinSingle",
    "zoomSniperSingle",
    "zoomMachineSingle",
    "zoomFlankSingle",
    "autoZoomSingle",
    "hybridZoomSingle",
    "tripletTrapper",
    "deca",
    "anniHybrid",
    "twinTrapperConqBot",
    "brutalizer",
    "twinAngleFighter",
    "anniSteamroll",
    "hexaContagion",
    "rangerObliterator",
    "builderArtillery",
    "builderMortar",
    "nanogun",
    "pebbler",
    "tripleHeavyTwin",
    "predatorDual",
    "assassinTrapGuard",
    "scythe",
    "trebuchet",
    "rewinder",
    "snipeBuilder",
    "twinAutoTwin",
    "anniIntercept",
    "xCarnivore",
    "bentTripleTwin",
    "poundTriplet",
    "invisibuilder",
    "megaConstruct",
    "machTriplet",
    "sniperTriplet",
    "flankTriTrap",
    "interceptTwin",
    "flankTriplet",
    "dreadning",
    "drivenaught",
    "interceptMach",
    "interceptSnipe",
    "flankBentTrapper",
    "machineAutoMachine",
    "interceptPound",
    "interceptTrap",
    "interceptFlank",
    "predaNightseeker",
    "invisianni",
    "pistol",
    "snipeception",
    "hawkBot",
    "ySpreadHunter",
    "xSpreadHunter",
    "pentaBorer",
    "pentaPunt",
    "pentaHewnPellet",
    "anniConqBot",
    "poundception",
    "pelletception",
    "destroyception",
    "overdriveHybrid",
    "gatlingMachGunner",
    "blasterMachGunner",
    "floodStream",
    "hybridFlooder",
    "interceptPellet",
    "puntStream",
    "wreckingBall",
    "hepta",
    "nailtrap",
    "invisispawner",
    "pentamancer",
    "blockSkimmer",
    "overdriveMaster",
    "staplegun",
    "overmaster",
    "battlenaught",
    "flankception",
    "pentaMachine",
    "hybridBentMachine",
    "twinDestroyer",
    "extraHeavyDouble",
    "puntTrapGuard",
    "twinBoost",
    "blower",
    "buttbuttin",
    "operator",
    "doubleception",
    "hexaception",
    "machPistol",
    "moreFortress",
    "gunAngle",
    "sparrowBot",
    "megaEngineer",
    "fatBattleship",
    "boomerEngineer",
    "machEngineer",
    "twinEngineer",
    "poundEngineer",
    "arsenal",
    "machArsenal",
    "megaArsenal",
    "autoOcto",
    "triArsenal",
    "trapGunner",
    "gigaArsenal",
    "triMachTrapper",
    "machMegaTrapper",
    "wideMortar",
    "autoMachGunner",
    "triMachArsenal",
    "trapMachGunner",
    "superMachGunner",
    "autoTripleTwin",
    "megamine",
    "gigaSmash",
    "constructArtillery",
    "streamClicker",
    "miniPuncher",
    "autoStream",
    "hybridSilo",
    "newBiohazard",
    "trapClicker",
    "buildception",
    "drivebridRifle",
    "gigaClicker",
    "miniRifle",
    "streamRifle",
    "miniClipper",
    "engineerArtillery",
    "invisiCarrier",
    "engineerContagion",
    "tripletHybrid",
    "pentaHybrid",
    "bentOverdrive",
    "flankPenta",
    "stalkRanger",
    "miniHunter",
    "invisibattleship",
    "flankSniper",
    "autoHunter",
    "cruisedrive",
    "huntception",
    "invisimaster",
    "masterBanshee",
    "builderBomber",
    "underbuild",
    "overbuild",
    "fastSteamroll",
    "miniHiveShooter",
    "megaHiveShooter",
    "hunterEagleBot",
    "nailGunRifle",
    "bent3",
    "sprayer3",
    "hunter3",
    "gigaContagion",
    "newDestroyerInsect",
    "twinFlankSniper",
    "tripleTwinSniper",
    "twinFlankAssassin",
    "autoRanger",
    "autoEngineer",
    "autoConstruct",
    "twinSnipeception",
    "autoTwinFlankSniper",
    "autoBooster",
    "surferBooster",
    "megaTrapClicker",
    "autoFighter",
    "autoPoundAngle",
    "autoSurfer",
    "hybridSkimmer",
    "hybridMiniHunter",
    "hybridPredator",
    "rocketFighter",
    "trapFighter",
    "hybridPredator",
    "minigun3",
    "trapGuardPursuer",
    "surfdrive",
    "doubleDual",
    "hunterPistol",
    "pentaArsenal",
    "destroyMini",
    "oscilloscope",
    "autoMatonStream",
    "gunHunter",
    "huntguard",
    "rifleHunter",
    "rifleception",
    "seismograph",
    "longOsci",
    "blasterFlooder",
    "wildfowler",
    "hexaDual",
    "boomerContagion",
    "poundOscilloscope",
    "phantasm",
    "rampart",
    "trapperHunter",
    "matchlock",
    "assassinSilo",
    "underPounder",
    "elamficitor",
    "poundFighter",
    "boostPoundAngle",
    "newSpider",
    "fatSurfer",
    "destAngle",
    "flankBoxer",
    "trimancer",
    "megaBattery",
    "subgunner",
    "autoTrapGunner",
    "hewnPunt",
    "constructContagion",
    "gunnerHunter",
    "hewnFerreter",
    "cruiserFerreter",
    "hewnGunCruiser",
    "gunnerDual",
    "gunnerPredator",
    "redistributor",
    "fighterSurfer",
    "trueMaster",
    "bansheeOverdrive",
    "twoHiveShooter",
    "megaColonist",
    "hexaTrio",
    "chargerReloader",
    "machHexaTrap",
    "masterLightning",
    "newColonist",
    "riflePreda",
    "fortressFrigate",
    "driveColonist",
    "autoMiniSwarmer",
    "miniMiniSwarmer",
    "megaShotgun",
    "twinStalk",
    "doubleContagion",
    "spitterFlank",
    "arsenalBarricade",
    "pentaFrigate",
    "twinMiniSwarm",
    "splitHiveShooter",
    "flooderBarricade",
    "gunnerception",
    "bentMiniSwarm",
    "snowstorm",
    "poundNailgun",
    "carpenter",
    "wideMoonburst",
    "bentFactory",
    "skimmerHiveShooter",
    "tripleShotSniper",
    "mechaBuilder",
    "borerception",
    "puntception",
    "assassinception",
    "blockClicker",
    "invisibleTri",
    "autoRocketTri",
    "twinSurfer",
    "autoTwinTri",
    "battleColonist",
    "autoBent",
    "bentception",
    "tripletSunburst",
    "cruiserSurfer",
    "autoTwin",
    "beehive2",
    "azgun",
    "miniColo",
    "nectarine",
    "miniVulc",
    "subTrapGuard",
    "submachine3",
    "foghornBuilder",
    "rocketTwinTri",
    "autoOverlord",
    "autoOscilloscope",
    "shellerAAGun",
    "vulcan",
    "autoSniper",
    "invisipistol",
    "arsenalClicker",
    "invisColonist",
    "gasser",
    "hornetHornet",
    "multitool",
    "mechaOverseer",
    "hybridPound",
    "hivemind",
    "megamind",
    "trapmind",
    "trapColonist",
    "inferno",
    "firenado",
    "typhoon",
    "snipemind",
    "poundOverdrive",
    "machOverdrive",
    "snipeInferno",
    "huntInferno",
    "backburner",
    "flaregun",
    "boomstick",
    "divider",
    "hybridTrapper",
    "minelayer",
    "blockLayer",
    "constructLayer",
    "chain",
    "flankCruiser",
    "driveNado",
    "backburnerTrap",
    "boomstick2",
    "flareshot",
    "gooseBot",
    "foghornConstruct",
    "trapFerreter",
    "machGigaTrapper",
    "droneception",
    "xTerminatorBot",
    "miniTwin",
    "zoomHunter",
    "zoomPredator",
    "zoomSounder",
    "zoomBattery",
    "swarmSnipeguard",
    "moreHybrid",
    "overception",
    "zoomShift",
    "machEngineer2",
    "machHivemind",
    "zoomStalk",
    "gunnerInfuser",
    "overTri",
    "spawnerception",
    "zoomCarnivore",
    "zoomOsci",
    "rangerHunter",
    "mechaOverseer",
    "cruiserception",
    "directorContagion",
    "autoSpawner",
    "contagionOverseer",
    "contagionOverlord",
    "contagionApprentice",
    "heavyDirector",
    "heatseeker",
    "swivel3",
    "swivel5",
    "sniperSwivel3",
    "swarmShotgun",
    "minigunception",
    "rocketInfuser",
    "surferInfuser",
    "fighterInfuser",
    "falconBot2",
    "swallowBot2",
    "autoFalconBot2",
    "ravenBot2",
    "hummingbirdBot2",
    "underSniper",
    "woodpeckBot2",
    "apprenticeTrapper",
    "navyist",
    "paratrooper",
    "guerrilla",
    "twinMarine",
    "flankParatrooper",
    "fastNavyist",
    "fasterNavyist",
    "rotary",
    "swivel4",
    "miniTrebuchet",
    "inventory",
    "twinLauncher",
    "foamGun",
    "artilleryShotgun",
    "driveBuckshot",
    "homingMachshot",
    "blockMusket",
    "bubbleGun",
    "triTrapception",
    "switcheroo1",
    "switcheroo2",
    "switcheroo3",
    "switcheroo4",
    "switcheroo5",
    "switcheroo6",
    "switcheroo7",
    "switcheroo8",
    "switcheroo9",
    "switcheroo10",
    "switcheroo11",
    "switcheroo12",
    "gatlingWoodpeckBot",
    "blasterWoodpeckBot",
    "streamLaser",
    "quadBuilder1",
    "triFlankTrap",
    "cartographer",
    "dual2",
    "assassinSounder",
    "ubercharge",
    "poundUbercharge",
    "invisHivemind",
    "heatRocketeer",
    "poundHeatseeker",
    "cart",
    "storkBot",
    "sounderCarrier",
    "fastEngineer",
    "wovenBasic",
    "wovenPenta",
    "bulletInferno",
    "sandCart",
    "bufferer",
    "harrower",
    "bentMini",
    "bentMachine",
    "propeller",
    "heronBot",
    "streamHunter",
    "snipeConstruct",
    "hybridBoomer",
    "twinAnni",
    "machConstruct",
    "heavyNavyist",
    "spiker",
    "autoTriplet",
    "flankBentSniper",
    "hybridBentSniper",
    "autoBentSniper",
    "bentAssassin",
    "pentaSniper",
    "doubleHewnDouble",
    "swarmSniper",
    "autoDirector",
    "hybridSniper",
    "spawnerContagion",
    "factoryContagion",
    "gatling3",
    "blaster3",
    "clicker3",
    "hybridRanger",
    "longSniperRifle",
    "hybridSniperRifle",
    "stackSpreadbow",
    "moreSpreadguard",
    "stackRefractor",
    "blockSpreadling",
    "autoTwinSpread",
    "littleTriRocket",
    "littleFighter",
    "manOWar",
    "bigUnderseer",
    "longPebbler",
    "bulwarkSword",
    "crowBot",
    "megaManOWar",
    "pyro",
    "swarmNavyist",
    "blunderbuss",
    "megaRifleClicker",
    "heavierRifle",
    "drivebridRifle",
    "hybridCarbine",
    "rifle3",
    "borerSail",
    "puntSail",
    "wideSail",
    "swarmMortar",
    "colony",
    "citadel",
    "sounderBattle",
    "flankHewnGunner",
    "droneHivemind",
    "flashbang",
    "doubleBuilder",
    "yTerminatorBot",
    "bentBuilder",
    "laserFlooder",
    "hybridLaser",
    "pelicanBot",
    "speeder",
    "boostFighter",
    "gunBooster",
    "autoGunAngle",
    "pelicanBot",
    "twinOverdrive",
    "shortRailgun",
    "bentSwarmTrapper",
    "swarmCarnivore",
    "trapperSniperRifle",
    "pyroContagion",
    "hybridRailgun",
    "auto2",
    "longRailgun",
    "megaRailgun",
    "swivel2",
    "twinMachine",
    "twinGatling",
    "twinBlaster",
    "bentGatling",
    "zoomRanger",
    "twinLaser",
    "littleArtillery",
    "twinFastGatling",
    "hotshotArtillery",
    "twinStream",
    "littleMortar",
    "hybridHotshot",
    "autoHotshot",
    "octoPound",
    "autoFlank",
    "autoHexaPound",
    "autoTriTrap",
    "flankObliterator",
    "hexaObliterator",
    "obliteratorInsect",
    "hexaSniper",
    "littleCannon",
    "octoDual",
    "moderator",
    "bigSheller",
    "fatBumper",
    "trapperSwarm",
    "growingRoadblock",
    "gunnerBuckshot",
    "accelRailgun",
    "spawnerOverdrive",
    "poundNavyist",
    "boosterDiver",
    "buildDiver",
    "autoFlankSniper",
    "gunnerPound",
    "flankSnipeception",
    "bentLauncher",
    "bentPounder",
    "bentDestroyer",
    "cannonLieutenant",
    "cannonMortar",
    "newGunScaler",
    "trapper3",
    "triBuilder",
    "twinFlankMach",
    "tripleTwinMach",
    "autoDoubleMach",
    "accelMini",
    "heavySunburst",
    "doubleGatling",
    "doubleBlaster",
    "accelStream",
    "accelAutoMaton",
    "ballista",
    "autoBallista",
    "hybridAutoBallista",
    "trapBallista",
    "hewnTwin",
    "newHewnDouble",
    "auto2mind",
    "megaColony",
    "invisBasher",
    "megaPlow",
    "hexaMachine",
    "octoMachine",
    "triSubMach",
    "hexaSubMach",
    "autoTriSub",
    "swivelMachine",
    "clickerMotolov",
    "twinHotshot",
    "poundHivemind",
    "invisiOsci",
    "trapper5",
    "triBoomer",
    "flankBoomer",
    "megaBoomer",
    "autoBoomer",
    "triEngineer",
    "triSnipeBuilder",
    "triConstruct",
    "triMachBuilder",
    "moreZoomHunter",
    "triInvisibuilder",
    "beedrive",
    "directdrive",
    "singleTrapper",
    "contagionAssassin",
    "poundIntercept",
    "flankAssassin",
    "hexaAssassin",
    "flankRanger",
    "heavyTwinSniper",
    "pentaCarrier",
    "twinPropeller",
    "single2",
    "megaTrapper3",
    "autoHexaSniper",
    "trapperSwivel3",
    "propellerHivemind",
    "pelletHivemind",
    "boostBomber",
    "heavyDoubleSniper",
    "flankConstruct",
    "hotshotAutoMaton",
    "doubleGunner",
    "singleMinishot",
    "triMegaTrapper",
    "lancer",
    "navigator",
    "assessor",
    "trailblazer",
    "vanguard",
    "serrator",
    "stiletto",
    "vantalancer",
    "singlePellet",
    "doubleRifle",
    "chasseur",
    "triLancer",
    "slayer",
    "knight",
    "mainstay",
    "waraxe",
    "jouster",
    "excalibur",
    "nunchuck",
    "duelist",
    "cutlass",
    "guillotine",
    "burst",
    "autoSlayer",
    "gunssessor",
    "avantgarde",
    "vindicator",
    "assegai",
    "hatchet",
    "caravan",
    "hexaBuilder",
    "flankGatling",
    "flankBlaster",
    "twinOsci",
    "half2",
    "autoObliterator",
    "obliteratorception",
    "autoLaser",
    "artilleryception",
    "twinRainbowBoi", // Joke
    "twinRandomColors", // Joke
    "basicInsect",
    "sniperInsect",
    "machInsect",
    "flankPoundception",
    "flooderSilo",
    "autoSilo",
    "trapInsect",
    "megaTrapInsect",
    "trapbang",
    "twinArsenal",
    "hewnGuntrap",
    "arsenalGuntrap",
    "gunbuilder",
    "accelLaser",
    "twinRailgun",
    "triAngleception",
    "autoPropeller",
    "propellerception",
    "nukeShooter",
    "starship",
    "sprayerception",
    "trapper2",
    "autoTrapper2",
    "blitz",
    "saber",
    "autoTank",
    "assassinBuilder",
    "singlePound",
    "autoSnipeBuilder",
    "octoSniper",
    "autoLittleArtillery",
    "minishotception",
    "autoBasic",
    "trapLittleSkimmer",
    "basicception",
    "littleArtillery3",
    "droneEngineer",
    "poundPenta",
    "autoMachTwin",
    "fatSkimmer",
    "hybridStalk",
    "underhunter",
    "snipeBoomer",
    "autoGatling",
    "gatlingception",
    "autoBlaster",
    "blasterception",
    "autoMiniVulc",
    "miniVulcception",
    "autoFlankMach",
    "flankMachception",
    "warhorse",
    "hexaLancer",
    "octoLancer",
    "blastAutoMachTrap",
    "hexaGatling",
    "hexaBlaster",
    "rpgRocketLauncher",
    "overpowerArty",
    "axolotl",
    "windstorm",
    "moreZoomSingle",
    "smashPound",
    "flankMini",
    "flankStream",
    "hexaMini",
    "autoFlankMini",
    "miniDouble",
    "doubleZoomSingle",
    "autoDoubleZoomSingle",
    "flankRifle",
    "hexaRifle",
  ];

  //let smashers = ['basic', "twin", "sniper"];
  let boosters = [ 'tri',
                'autoTri',
                'booster',
                'surfer',
                'falconBot2',
                'eagleBot',
                'poundAngle',
                'triRocket',
                'diver',
                'boostRocket',
                'brutalizer',
                'destAngle',
                'propeller',
                'littleTriRocket',
                'manOWar',
                'littleFighter',
                'megaManOWar',
                'fighter',
                'bomber',
                'marine',
                'twinTri',
                'gunAngle',
                'overTri',
                'woodpeckBot2',
                'starbomber',
                'builderBomber',
                'twinBoost',
                'sparrowBot',
                'gunBooster',
                'speeder',
                'boostFighter',
                'rocketFighter',
                'autoRocketTri',
                'rocketTwinTri',
                'rocketInfuser',
                'ravenBot2',
                'surferBooster',
                'autoBooster',
                'boostPoundAngle',
                'autoSurfer',
                'surfdrive',
                'fatSurfer',
                'fighterSurfer',
                'twinSurfer',
                'cruiserSurfer',
                'surferInfuser',
                'swallowBot2',
                'twinAngleFighter',
                'autoTwinTri',
                'gunnerInfuser',
                'autoFighter',
                'trapFighter',
                 'poundFighter',
                'hawkBot',
                'gooseBot',
                'autoGunAngle',
                'autoPoundAngle',
                'autoFalconBot2',
                'invisibleTri',
                'twinMarine',
                'gatlingWoodpeckBot',
                'blasterWoodpeckBot',
                'storkBot',
                'falconBot',
                'hunterEagleBot',
                'hummingbirdBot2',
                'heronBot',
                'crowBot',
                'pelicanBot',
                'boosterDiver',
                'buildDiver',
                'twinPropeller',
                'propellerHivemind',
                'boostBomber',
                'trailblazer',
                'vanguard',
                'triAngleception',
                'autoPropeller',
                'propellerception'
            ]
  switch (tank) {
    case "norm":
      return tanks[Math.floor(Math.random() * tanks.length)];
    case "smash":
      return tanks[Math.floor(Math.random() * tanks.length)];
    case "boost":
      return boosters[Math.floor(Math.random() * boosters.length)];
  }
};
exports.randomRange = (min, max) => {
    return Math.random() * (max - min) + min;
};

exports.irandom = i => {
    let max = Math.floor(i);
    return Math.floor(Math.random() * (max + 1)); //Inclusive
};

exports.irandomRange = (min, max) => {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min; //Inclusive
};

exports.gauss = (mean, deviation) => {
    let x1, x2, w;
    do {
        x1 = 2*Math.random() - 1;
        x2 = 2*Math.random() - 1;
        w = x1 * x1 + x2 * x2;
    } while (0 == w || w >= 1);

    w = Math.sqrt(-2 * Math.log(w) / w);
    return mean + deviation * x1 * w;
};

exports.gaussInverse = (min, max, clustering) => {
    let range = max - min;
    let output = exports.gauss(0, range / clustering);

    while (output < 0) {
        output += range;
    }
    
    while (output > range) {
        output -= range;
    }
    
    return output + min;
};

exports.gaussRing = (radius, clustering) => {
    let r = exports.random(Math.PI * 2);
    let d = exports.gauss(radius, radius*clustering);
    return {
        x: d * Math.cos(r),
        y: d * Math.sin(r),
    };
};

exports.chance = prob => {
    return exports.random(1) < prob;
};

exports.dice = sides => {
    return exports.random(sides) < 1;
};

exports.choose = arr => {
    return arr[exports.irandom(arr.length - 1)];
};

exports.chooseN = (arr, n) => {
    let o = [];
    for (let i=0; i<n; i++) {
        o.push(arr.splice(exports.irandom(arr.length - 1), 1)[0]);
    }
    return o;
};

exports.chooseChance = (...arg) => {
    let totalProb = 0;
    arg.forEach(function(value) { totalProb += value; });
    let answer = exports.random(totalProb);
    for (let i=0; i<arg.length; i++) {
        if (answer<arg[i]) return i;
        answer -= arg[i];
    }
};


exports.chooseBotName = () => {
    return exports.choose([
       ",!foO",
",#teamtrees",
",.",
",.-.",
",...",
",0",
",1",
",666",
",:D",
",A Settlement Needs Your Help",
",A named player",
",AHHHHHH!",
",AK-47",
",AMIGOS",
",Aleph Null",
",Alexis",
",Algiz",
",Alice",
",Allah Is King",
",Alpha",
",Am I Sinbadx?",
",An unnamed player",
",Angel",
",Are you okay?",
",ArenaC",
",BOMBS AWAY",
",BT TOKEN: THISISLIE",
",BUSTER WOLF",
",Baller",
",Balloon",
",Banarama",
",Bar Milk",
",Basic",
",Bee",
",Berkanan",
",Blank",
",Bob",
",BrOBer The Prod",
",Bravo",
",Brian",
",Broccoli",
",Brotherhood of Steel",
",Bruh Monument",
",CATS",
",CJ",
",COPPA Sucks",
",CUCK",
",CX Fan",
",Caesar",
",Canada > USA",
",Captian",
",Careenervirus",
",Carmen",
",Charlie",
",Coronavirus",
",Creeper, Aw Man",
",D:",
",DJ-Nate",
",DJVI",
",DO QUESTS",
",DOGE",
",Dagaz",
",Dagaz 2.0",
",David",
",Decagon?",
",Delta",
",Derp",
",Dex Arson",
",Discord",
",Disposition",
",Dumb",
",Echo",
",Edith",
",Ehwaz",
",Electrodynamix",
",Elmo is gone",
",F-777",
",FEED ME",
",Faaip de Oiad",
",Fallen AI",
",FeZTi Fan",
",FeZTiVAl",
",FeZTivAL",
",FeZtiVaL",
",ForeverBound",
",Foxtrot",
",Freddy",
",Friend pls",
",Friends?",
",GABE",
",GOKU",
",Gabogc",
",Get bonked",
",Give Me Wings",
",Gustav",
",Hagalaz",
",Halal Certified Tank",
",Hammer",
",Have mercy...",
",Have you considered how many of us you killed",
",Helga",
",HerrrrrrrH",
",Hotel",
",Hug Me",
",I am easter egg lol",
",I have candy",
",I forgor",
",IRS",
",Ight Bro",
",Im scary",
",India",
",Insanity",
",Internet Explorer",
",JTG",
",Jake",
",Jambi",
",Janet",
",Jera",
",Joe Mamma",
",Judith",
",Juliet",
",KING CRIMSON!",
",KOA",
",Kilo",
",Kim Jong-Un",
",King of Pros",
",Knoz",
",LOCO",
",LOL",
",Lateralus",
",Liberty Prime",
",Lima",
",Little Red Rocket",
",Lorenzo",
",Lucas",
",M8",
",MATRIX",
",MJK",
",Magikarp",
",Mahlo Cardinal?",
",Mango",
",Mantra",
",Mary",
",Mew",
",Mike",
",MrBeast",
",NO U",
",NO WITCH-HUNTING",
",Neo",
",Nerf danger plx",
",NoCopyrightSounds",
",Nooblet",
",Nora",
",Nova",
",November",
",ORA ORA ORA",
",O_O",
",Olivia",
",Oscar",
",Oswald Veblen",
",Our World of Tanks",
",OwO",
",PEST_YT",
",PP Tank",
",Papa",
",Paradox",
",Peekachu",
",Peter",
",Popo",
",Quebec",
",Queen",
",Railroad",
",Rake",
",Ramen",
",Real AI",
",Real CreepyDaPolyplanet",
",Real Dark Knight",
",Real Despacit.io",
",Real Hellcat",
",Real Kitty!",
",Red Hot Chili Pepper",
",Reflection",
",Road To 10m",
",Roger",
",Romeo",
",Rosetta Stoned",
",Rubrub",
",Ruthless",
",SPICY RAMEN",
",Salsa Verde",
",Sierra",
",Sinx",
",Slayer",
",Solomon",
",Spree",
",Steven Universe",
",Sub 2 Pewdiepie",
",Sucko mode",
",Suzanne",
",T-REX",
",T-Series",
",TEST",
",THE WORLD!",
",TOUCAN",
",Tango",
",Tank A",
",The Audacity of this tank",
",The Common Cold",
",The Grudge",
",The Nameless",
",The Patient",
",The Pot",
",TheFatRat",
",Theory of Everything",
",Toast",
",Tommy",
",Totally Not A Bot",
",Trans Rights",
",Triad",
",Tyson",
",UWU OWO LMFAOOOOOO",
",Uniform",
",Ursula",
",UwU",
",U S A",
",V",
",Vanze",
",Vicarious",
",Victor",
",Vincent",
",Vogelaj",
",W = Team",
",WOOT",
",Waterflame",
",What?",
",Whiskey",
",Wilhelm",
",Windows 98",
",Womp Womp",
",X-Ray",
",Xerxes",
",Y",
",YouRIP",
",Yvonne",
",ZA WARUDO!",
",Zachary",
",Zplit",
",Zulu",
",[AI]",
",[GZ] team",
",[IX] clan",
",[MG] PRO TEAM",
",[MG] Team",
",[insert creative name]",
",a salty discord kid",
",agar.io",
",angel",
",arras > diep",
",arras.io",
",best",
",big me!",
",bob",
",boi",
",brogle",
",bruh moment",
",buff arena closer",
",buff basic",
",colombia",
",cookie",
",cool",
",crasher",
",developer",
",die",
",dont touch me",
",dragons go mlem",
",e",
",facu++",
",fezti fan",
",final destination, fox only",
",food",
",g.bit_less_reload, g.bit_less_reload",
",g.win",
",green square",
",hell",
",hmst",
",how to get testbed?",
",iXPLODE",
",illuminati",
",im beef",
",im new",
",jotaro kujo",
",jumla",
",k",
",kek",
",king of diep",
",king slayer",
",kitten",
",koala",
",kokak",
",leonardo",
",llego el pro!",
",look behind you",
",luka modric",
",max",
",meme",
",mf=r",
",mm",
",name",
",no",
",no team Kill",
",noob",
",novice",
",ok boomer",
",oof",
",penguinz0",
",pet",
",poyo",
",rIsKy",
",read and u ded",
",readd aegis",
",road to 1m",
",ruler of tanks",
",rush",
",sael savage",
",salty",
",satan",
",squirt",
",stink",
",summoner",
",taal volcano",
",take this L",
",team??!",
",teamplz",
",toon",
",trump",
",ur mom",
",walmart man",
",why",
",wommy aRaas",
",¡AY PAPI!",
",¡Vamos!",
",¿Equipo?",
",✈",
",𝕯𝖆𝖙 𝕺𝖓𝖊 𝕭𝖔𝖎",
",😈",
      
    ]);
};
exports.chooseBotName2 = () => {
    return exports.choose([
     'Arena Closer'
    ]);
};

exports.chooseBossName = (code, n) => {
    switch (code) {
    case 'a':
    return exports.chooseN([
        'Archimedes',
        'Akilina',
        'Anastasios',
        'Athena',
        'Alkaios',
        'Amyntas',
        'Aniketos',
        'Artemis',
        'Anaxagoras',
        'Apollon',
      

    ], n);
    case 'castle':
    return exports.chooseN([
        'Berezhany',
        'Lutsk',
        'Dobromyl',
        'Akkerman',
        'Palanok',
        'Zolochiv',
        'Palanok',
        'Mangup',
        'Olseko',
        'Brody',
        'Isiaslav',
        'Kaffa',
        'Bilhorod',
    ], n);
    default: return 'God';
    
  case 'special':
    return exports.chooseN([
        'Hera',
        'Zeus',
        'Ares',
        'Apollo',
        'Atlas',
        'Unknown',
        '???',
       
    ], n);
    
    }
};
